// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: mds.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FastpathRequest_Op int32

const (
	FastpathRequest_INVALID    FastpathRequest_Op = 0
	FastpathRequest_COMMIT_TXN FastpathRequest_Op = 1
	FastpathRequest_ABORT_TXN  FastpathRequest_Op = 2
	FastpathRequest_OPEN_TXN   FastpathRequest_Op = 3
	FastpathRequest_GET        FastpathRequest_Op = 4
	FastpathRequest_SET        FastpathRequest_Op = 5
	FastpathRequest_DELETE     FastpathRequest_Op = 6
	FastpathRequest_LIST       FastpathRequest_Op = 7
)

// Enum value maps for FastpathRequest_Op.
var (
	FastpathRequest_Op_name = map[int32]string{
		0: "INVALID",
		1: "COMMIT_TXN",
		2: "ABORT_TXN",
		3: "OPEN_TXN",
		4: "GET",
		5: "SET",
		6: "DELETE",
		7: "LIST",
	}
	FastpathRequest_Op_value = map[string]int32{
		"INVALID":    0,
		"COMMIT_TXN": 1,
		"ABORT_TXN":  2,
		"OPEN_TXN":   3,
		"GET":        4,
		"SET":        5,
		"DELETE":     6,
		"LIST":       7,
	}
)

func (x FastpathRequest_Op) Enum() *FastpathRequest_Op {
	p := new(FastpathRequest_Op)
	*p = x
	return p
}

func (x FastpathRequest_Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FastpathRequest_Op) Descriptor() protoreflect.EnumDescriptor {
	return file_mds_proto_enumTypes[0].Descriptor()
}

func (FastpathRequest_Op) Type() protoreflect.EnumType {
	return &file_mds_proto_enumTypes[0]
}

func (x FastpathRequest_Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FastpathRequest_Op.Descriptor instead.
func (FastpathRequest_Op) EnumDescriptor() ([]byte, []int) {
	return file_mds_proto_rawDescGZIP(), []int{5, 0}
}

type LoginChallenge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Challenge []byte `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	Version   string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *LoginChallenge) Reset() {
	*x = LoginChallenge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mds_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginChallenge) ProtoMessage() {}

func (x *LoginChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_mds_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginChallenge.ProtoReflect.Descriptor instead.
func (*LoginChallenge) Descriptor() ([]byte, []int) {
	return file_mds_proto_rawDescGZIP(), []int{0}
}

func (x *LoginChallenge) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *LoginChallenge) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Store     string `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	MuxWidth  uint32 `protobuf:"varint,4,opt,name=mux_width,json=muxWidth,proto3" json:"mux_width,omitempty"`
}

func (x *Login) Reset() {
	*x = Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mds_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login) ProtoMessage() {}

func (x *Login) ProtoReflect() protoreflect.Message {
	mi := &file_mds_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login.ProtoReflect.Descriptor instead.
func (*Login) Descriptor() ([]byte, []int) {
	return file_mds_proto_rawDescGZIP(), []int{1}
}

func (x *Login) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *Login) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Login) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Login) GetMuxWidth() uint32 {
	if x != nil {
		return x.MuxWidth
	}
	return 0
}

type LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok     bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Region string `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Error  string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mds_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mds_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_mds_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *LoginResponse) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *LoginResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lane          uint32             `protobuf:"varint,1,opt,name=lane,proto3" json:"lane,omitempty"`
	Program       string             `protobuf:"bytes,2,opt,name=program,proto3" json:"program,omitempty"`
	Data          string             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	FastpathReqid uint64             `protobuf:"varint,4,opt,name=fastpath_reqid,json=fastpathReqid,proto3" json:"fastpath_reqid,omitempty"`
	FastpathBatch []*FastpathRequest `protobuf:"bytes,5,rep,name=fastpath_batch,json=fastpathBatch,proto3" json:"fastpath_batch,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mds_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_mds_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_mds_proto_rawDescGZIP(), []int{3}
}

func (x *Request) GetLane() uint32 {
	if x != nil {
		return x.Lane
	}
	return 0
}

func (x *Request) GetProgram() string {
	if x != nil {
		return x.Program
	}
	return ""
}

func (x *Request) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Request) GetFastpathReqid() uint64 {
	if x != nil {
		return x.FastpathReqid
	}
	return 0
}

func (x *Request) GetFastpathBatch() []*FastpathRequest {
	if x != nil {
		return x.FastpathBatch
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lane uint32 `protobuf:"varint,1,opt,name=lane,proto3" json:"lane,omitempty"`
	// Types that are assignable to Body:
	//	*Response_Error
	//	*Response_Output
	Body          isResponse_Body     `protobuf_oneof:"body"`
	FastpathReqid uint64              `protobuf:"varint,4,opt,name=fastpath_reqid,json=fastpathReqid,proto3" json:"fastpath_reqid,omitempty"`
	FastpathBatch []*FastpathResponse `protobuf:"bytes,5,rep,name=fastpath_batch,json=fastpathBatch,proto3" json:"fastpath_batch,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mds_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_mds_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_mds_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetLane() uint32 {
	if x != nil {
		return x.Lane
	}
	return 0
}

func (m *Response) GetBody() isResponse_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *Response) GetError() *ErrorResponse {
	if x, ok := x.GetBody().(*Response_Error); ok {
		return x.Error
	}
	return nil
}

func (x *Response) GetOutput() string {
	if x, ok := x.GetBody().(*Response_Output); ok {
		return x.Output
	}
	return ""
}

func (x *Response) GetFastpathReqid() uint64 {
	if x != nil {
		return x.FastpathReqid
	}
	return 0
}

func (x *Response) GetFastpathBatch() []*FastpathResponse {
	if x != nil {
		return x.FastpathBatch
	}
	return nil
}

type isResponse_Body interface {
	isResponse_Body()
}

type Response_Error struct {
	Error *ErrorResponse `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type Response_Output struct {
	Output string `protobuf:"bytes,3,opt,name=output,proto3,oneof"`
}

func (*Response_Error) isResponse_Body() {}

func (*Response_Output) isResponse_Body() {}

type FastpathRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op          FastpathRequest_Op   `protobuf:"varint,1,opt,name=op,proto3,enum=mds.FastpathRequest_Op" json:"op,omitempty"`
	TxnId       uint64               `protobuf:"varint,2,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	IsPrimary   bool                 `protobuf:"varint,3,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	Kvp         []*KeyValuePair      `protobuf:"bytes,4,rep,name=kvp,proto3" json:"kvp,omitempty"`
	ListOptions *FastpathListOptions `protobuf:"bytes,5,opt,name=list_options,json=listOptions,proto3" json:"list_options,omitempty"`
}

func (x *FastpathRequest) Reset() {
	*x = FastpathRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mds_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FastpathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FastpathRequest) ProtoMessage() {}

func (x *FastpathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mds_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FastpathRequest.ProtoReflect.Descriptor instead.
func (*FastpathRequest) Descriptor() ([]byte, []int) {
	return file_mds_proto_rawDescGZIP(), []int{5}
}

func (x *FastpathRequest) GetOp() FastpathRequest_Op {
	if x != nil {
		return x.Op
	}
	return FastpathRequest_INVALID
}

func (x *FastpathRequest) GetTxnId() uint64 {
	if x != nil {
		return x.TxnId
	}
	return 0
}

func (x *FastpathRequest) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *FastpathRequest) GetKvp() []*KeyValuePair {
	if x != nil {
		return x.Kvp
	}
	return nil
}

func (x *FastpathRequest) GetListOptions() *FastpathListOptions {
	if x != nil {
		return x.ListOptions
	}
	return nil
}

type FastpathListOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit     uint32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Reverse   bool   `protobuf:"varint,2,opt,name=reverse,proto3" json:"reverse,omitempty"`
	WantValue bool   `protobuf:"varint,3,opt,name=want_value,json=wantValue,proto3" json:"want_value,omitempty"`
}

func (x *FastpathListOptions) Reset() {
	*x = FastpathListOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mds_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FastpathListOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FastpathListOptions) ProtoMessage() {}

func (x *FastpathListOptions) ProtoReflect() protoreflect.Message {
	mi := &file_mds_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FastpathListOptions.ProtoReflect.Descriptor instead.
func (*FastpathListOptions) Descriptor() ([]byte, []int) {
	return file_mds_proto_rawDescGZIP(), []int{6}
}

func (x *FastpathListOptions) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FastpathListOptions) GetReverse() bool {
	if x != nil {
		return x.Reverse
	}
	return false
}

func (x *FastpathListOptions) GetWantValue() bool {
	if x != nil {
		return x.WantValue
	}
	return false
}

type FastpathResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxnId uint64          `protobuf:"varint,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	Error *ErrorResponse  `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Kvp   []*KeyValuePair `protobuf:"bytes,3,rep,name=kvp,proto3" json:"kvp,omitempty"`
}

func (x *FastpathResponse) Reset() {
	*x = FastpathResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mds_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FastpathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FastpathResponse) ProtoMessage() {}

func (x *FastpathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mds_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FastpathResponse.ProtoReflect.Descriptor instead.
func (*FastpathResponse) Descriptor() ([]byte, []int) {
	return file_mds_proto_rawDescGZIP(), []int{7}
}

func (x *FastpathResponse) GetTxnId() uint64 {
	if x != nil {
		return x.TxnId
	}
	return 0
}

func (x *FastpathResponse) GetError() *ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *FastpathResponse) GetKvp() []*KeyValuePair {
	if x != nil {
		return x.Kvp
	}
	return nil
}

type KeyValuePair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *KeyValuePair) Reset() {
	*x = KeyValuePair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mds_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyValuePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValuePair) ProtoMessage() {}

func (x *KeyValuePair) ProtoReflect() protoreflect.Message {
	mi := &file_mds_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValuePair.ProtoReflect.Descriptor instead.
func (*KeyValuePair) Descriptor() ([]byte, []int) {
	return file_mds_proto_rawDescGZIP(), []int{8}
}

func (x *KeyValuePair) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyValuePair) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type StoreInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cluster  string `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Subspace string `protobuf:"bytes,2,opt,name=subspace,proto3" json:"subspace,omitempty"`
}

func (x *StoreInfo) Reset() {
	*x = StoreInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mds_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreInfo) ProtoMessage() {}

func (x *StoreInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mds_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreInfo.ProtoReflect.Descriptor instead.
func (*StoreInfo) Descriptor() ([]byte, []int) {
	return file_mds_proto_rawDescGZIP(), []int{9}
}

func (x *StoreInfo) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *StoreInfo) GetSubspace() string {
	if x != nil {
		return x.Subspace
	}
	return ""
}

type ErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Retryable   bool   `protobuf:"varint,2,opt,name=retryable,proto3" json:"retryable,omitempty"`
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mds_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mds_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_mds_proto_rawDescGZIP(), []int{10}
}

func (x *ErrorResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ErrorResponse) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

type Cluster struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Primary  *ClusterRegion   `protobuf:"bytes,1,opt,name=primary,proto3" json:"primary,omitempty"`
	Replicas []*ClusterRegion `protobuf:"bytes,2,rep,name=replicas,proto3" json:"replicas,omitempty"`
}

func (x *Cluster) Reset() {
	*x = Cluster{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mds_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster) ProtoMessage() {}

func (x *Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_mds_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cluster.ProtoReflect.Descriptor instead.
func (*Cluster) Descriptor() ([]byte, []int) {
	return file_mds_proto_rawDescGZIP(), []int{11}
}

func (x *Cluster) GetPrimary() *ClusterRegion {
	if x != nil {
		return x.Primary
	}
	return nil
}

func (x *Cluster) GetReplicas() []*ClusterRegion {
	if x != nil {
		return x.Replicas
	}
	return nil
}

type ClusterRegion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Region string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Config string `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *ClusterRegion) Reset() {
	*x = ClusterRegion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mds_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterRegion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterRegion) ProtoMessage() {}

func (x *ClusterRegion) ProtoReflect() protoreflect.Message {
	mi := &file_mds_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterRegion.ProtoReflect.Descriptor instead.
func (*ClusterRegion) Descriptor() ([]byte, []int) {
	return file_mds_proto_rawDescGZIP(), []int{12}
}

func (x *ClusterRegion) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ClusterRegion) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type UserRoleList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roles []string `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
}

func (x *UserRoleList) Reset() {
	*x = UserRoleList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mds_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRoleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRoleList) ProtoMessage() {}

func (x *UserRoleList) ProtoReflect() protoreflect.Message {
	mi := &file_mds_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRoleList.ProtoReflect.Descriptor instead.
func (*UserRoleList) Descriptor() ([]byte, []int) {
	return file_mds_proto_rawDescGZIP(), []int{13}
}

func (x *UserRoleList) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type StoreRoleList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roles         []string `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	ReadonlyRoles []string `protobuf:"bytes,2,rep,name=readonly_roles,json=readonlyRoles,proto3" json:"readonly_roles,omitempty"`
}

func (x *StoreRoleList) Reset() {
	*x = StoreRoleList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mds_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreRoleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRoleList) ProtoMessage() {}

func (x *StoreRoleList) ProtoReflect() protoreflect.Message {
	mi := &file_mds_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRoleList.ProtoReflect.Descriptor instead.
func (*StoreRoleList) Descriptor() ([]byte, []int) {
	return file_mds_proto_rawDescGZIP(), []int{14}
}

func (x *StoreRoleList) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *StoreRoleList) GetReadonlyRoles() []string {
	if x != nil {
		return x.ReadonlyRoles
	}
	return nil
}

var File_mds_proto protoreflect.FileDescriptor

var file_mds_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6d, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x64, 0x73,
	0x22, 0x48, 0x0a, 0x0e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e,
	0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x77, 0x0a, 0x05, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x75, 0x78, 0x5f, 0x77, 0x69,
	0x64, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6d, 0x75, 0x78, 0x57, 0x69,
	0x64, 0x74, 0x68, 0x22, 0x4d, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x02, 0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0xaf, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6c, 0x61,
	0x6e, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x25, 0x0a, 0x0e, 0x66, 0x61, 0x73, 0x74, 0x70, 0x61, 0x74, 0x68, 0x5f, 0x72, 0x65, 0x71,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x66, 0x61, 0x73, 0x74, 0x70, 0x61,
	0x74, 0x68, 0x52, 0x65, 0x71, 0x69, 0x64, 0x12, 0x3b, 0x0a, 0x0e, 0x66, 0x61, 0x73, 0x74, 0x70,
	0x61, 0x74, 0x68, 0x5f, 0x62, 0x61, 0x74, 0x63, 0x68, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x6d, 0x64, 0x73, 0x2e, 0x46, 0x61, 0x73, 0x74, 0x70, 0x61, 0x74, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0d, 0x66, 0x61, 0x73, 0x74, 0x70, 0x61, 0x74, 0x68, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x22, 0xd1, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x6c, 0x61, 0x6e, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x64, 0x73, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x18, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x66,
	0x61, 0x73, 0x74, 0x70, 0x61, 0x74, 0x68, 0x5f, 0x72, 0x65, 0x71, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0d, 0x66, 0x61, 0x73, 0x74, 0x70, 0x61, 0x74, 0x68, 0x52, 0x65, 0x71,
	0x69, 0x64, 0x12, 0x3c, 0x0a, 0x0e, 0x66, 0x61, 0x73, 0x74, 0x70, 0x61, 0x74, 0x68, 0x5f, 0x62,
	0x61, 0x74, 0x63, 0x68, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x64, 0x73,
	0x2e, 0x46, 0x61, 0x73, 0x74, 0x70, 0x61, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x52, 0x0d, 0x66, 0x61, 0x73, 0x74, 0x70, 0x61, 0x74, 0x68, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x42, 0x06, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0xba, 0x02, 0x0a, 0x0f, 0x46, 0x61, 0x73,
	0x74, 0x70, 0x61, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x02,
	0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x6d, 0x64, 0x73, 0x2e, 0x46,
	0x61, 0x73, 0x74, 0x70, 0x61, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4f,
	0x70, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x78, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x78, 0x6e, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x69, 0x73, 0x5f, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x69, 0x73, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x23, 0x0a, 0x03, 0x6b,
	0x76, 0x70, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x64, 0x73, 0x2e, 0x4b,
	0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x61, 0x69, 0x72, 0x52, 0x03, 0x6b, 0x76, 0x70,
	0x12, 0x3b, 0x0a, 0x0c, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x64, 0x73, 0x2e, 0x46, 0x61, 0x73,
	0x74, 0x70, 0x61, 0x74, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x0b, 0x6c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x66, 0x0a,
	0x02, 0x4f, 0x70, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00,
	0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x4f, 0x4d, 0x4d, 0x49, 0x54, 0x5f, 0x54, 0x58, 0x4e, 0x10, 0x01,
	0x12, 0x0d, 0x0a, 0x09, 0x41, 0x42, 0x4f, 0x52, 0x54, 0x5f, 0x54, 0x58, 0x4e, 0x10, 0x02, 0x12,
	0x0c, 0x0a, 0x08, 0x4f, 0x50, 0x45, 0x4e, 0x5f, 0x54, 0x58, 0x4e, 0x10, 0x03, 0x12, 0x07, 0x0a,
	0x03, 0x47, 0x45, 0x54, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x45, 0x54, 0x10, 0x05, 0x12,
	0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x06, 0x12, 0x08, 0x0a, 0x04, 0x4c,
	0x49, 0x53, 0x54, 0x10, 0x07, 0x22, 0x64, 0x0a, 0x13, 0x46, 0x61, 0x73, 0x74, 0x70, 0x61, 0x74,
	0x68, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x77, 0x61, 0x6e, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x77, 0x61, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x78, 0x0a, 0x10, 0x46,
	0x61, 0x73, 0x74, 0x70, 0x61, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x15, 0x0a, 0x06, 0x74, 0x78, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x74, 0x78, 0x6e, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x64, 0x73, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x23, 0x0a, 0x03, 0x6b, 0x76, 0x70, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x6d, 0x64, 0x73, 0x2e, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x61, 0x69, 0x72,
	0x52, 0x03, 0x6b, 0x76, 0x70, 0x22, 0x36, 0x0a, 0x0c, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x50, 0x61, 0x69, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x41, 0x0a,
	0x09, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x75, 0x62, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x75, 0x62, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x22, 0x4f, 0x0a, 0x0d, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x74, 0x72, 0x79, 0x61, 0x62, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x72, 0x65, 0x74, 0x72, 0x79, 0x61, 0x62, 0x6c,
	0x65, 0x22, 0x67, 0x0a, 0x07, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x07,
	0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x6d, 0x64, 0x73, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x52, 0x07, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x2e, 0x0a, 0x08, 0x72, 0x65,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d,
	0x64, 0x73, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x52, 0x08, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x22, 0x3f, 0x0a, 0x0d, 0x43, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x24, 0x0a, 0x0c, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72,
	0x6f, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65,
	0x73, 0x22, 0x4c, 0x0a, 0x0d, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x61, 0x64,
	0x6f, 0x6e, 0x6c, 0x79, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0d, 0x72, 0x65, 0x61, 0x64, 0x6f, 0x6e, 0x6c, 0x79, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x42,
	0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mds_proto_rawDescOnce sync.Once
	file_mds_proto_rawDescData = file_mds_proto_rawDesc
)

func file_mds_proto_rawDescGZIP() []byte {
	file_mds_proto_rawDescOnce.Do(func() {
		file_mds_proto_rawDescData = protoimpl.X.CompressGZIP(file_mds_proto_rawDescData)
	})
	return file_mds_proto_rawDescData
}

var file_mds_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mds_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_mds_proto_goTypes = []interface{}{
	(FastpathRequest_Op)(0),     // 0: mds.FastpathRequest.Op
	(*LoginChallenge)(nil),      // 1: mds.LoginChallenge
	(*Login)(nil),               // 2: mds.Login
	(*LoginResponse)(nil),       // 3: mds.LoginResponse
	(*Request)(nil),             // 4: mds.Request
	(*Response)(nil),            // 5: mds.Response
	(*FastpathRequest)(nil),     // 6: mds.FastpathRequest
	(*FastpathListOptions)(nil), // 7: mds.FastpathListOptions
	(*FastpathResponse)(nil),    // 8: mds.FastpathResponse
	(*KeyValuePair)(nil),        // 9: mds.KeyValuePair
	(*StoreInfo)(nil),           // 10: mds.StoreInfo
	(*ErrorResponse)(nil),       // 11: mds.ErrorResponse
	(*Cluster)(nil),             // 12: mds.Cluster
	(*ClusterRegion)(nil),       // 13: mds.ClusterRegion
	(*UserRoleList)(nil),        // 14: mds.UserRoleList
	(*StoreRoleList)(nil),       // 15: mds.StoreRoleList
}
var file_mds_proto_depIdxs = []int32{
	6,  // 0: mds.Request.fastpath_batch:type_name -> mds.FastpathRequest
	11, // 1: mds.Response.error:type_name -> mds.ErrorResponse
	8,  // 2: mds.Response.fastpath_batch:type_name -> mds.FastpathResponse
	0,  // 3: mds.FastpathRequest.op:type_name -> mds.FastpathRequest.Op
	9,  // 4: mds.FastpathRequest.kvp:type_name -> mds.KeyValuePair
	7,  // 5: mds.FastpathRequest.list_options:type_name -> mds.FastpathListOptions
	11, // 6: mds.FastpathResponse.error:type_name -> mds.ErrorResponse
	9,  // 7: mds.FastpathResponse.kvp:type_name -> mds.KeyValuePair
	13, // 8: mds.Cluster.primary:type_name -> mds.ClusterRegion
	13, // 9: mds.Cluster.replicas:type_name -> mds.ClusterRegion
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_mds_proto_init() }
func file_mds_proto_init() {
	if File_mds_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mds_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginChallenge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mds_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mds_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mds_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mds_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mds_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FastpathRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mds_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FastpathListOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mds_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FastpathResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mds_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyValuePair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mds_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mds_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mds_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cluster); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mds_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterRegion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mds_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRoleList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mds_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreRoleList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_mds_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*Response_Error)(nil),
		(*Response_Output)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mds_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mds_proto_goTypes,
		DependencyIndexes: file_mds_proto_depIdxs,
		EnumInfos:         file_mds_proto_enumTypes,
		MessageInfos:      file_mds_proto_msgTypes,
	}.Build()
	File_mds_proto = out.File
	file_mds_proto_rawDesc = nil
	file_mds_proto_goTypes = nil
	file_mds_proto_depIdxs = nil
}
